name: cts
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

#  storage
  get_storage: ^2.0.3
#  localstorage: ^3.0.6
#  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1

  get: ^4.6.1
  dio: ^4.0.4
  encrypt: ^5.0.1
  intl: ^0.17.0
  local_auth: ^2.1.0
  contained_tab_bar_view: ^0.8.0
  platform: ^3.1.0
  syncfusion_flutter_pdfviewer: ^20.2.40-beta
#  flutter_sound_lite: ^8.5.0
  flutter_sound: ^9.2.13
  permission_handler: ^10.0.0
  path_provider: ^2.0.9
  flutter_colorpicker: ^1.0.3
  flutter_typeahead: ^4.0.0
  dropdown_button2:
  top_snackbar_flutter: ^2.1.1

#  drag_and_drop_lists: ^0.2.1
  drag_and_drop_lists: ^0.3.1
  webview_flutter: ^3.0.4
  signature: ^5.0.1
  file_picker: ^5.0.1
  restart_app: ^1.1.0
  flutter_phoenix: ^1.0.0


#  cached_network_image: ^3.2.2
  cached_memory_image: ^1.3.1

  pdfx: any
  uuid: ^3.0.6
  flutter_svg: ">=1.0.0"
  path_drawing: ^1.0.0
  internet_file: ^1.2.0
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/json/
  
  fonts:
     - family: Bahij_light
       fonts:
         - asset: assets/fonts/Bahij_TheSansArabic-Plain.ttf
     - family: Bahij_bold
       fonts:
        - asset: assets/fonts/bahijthesansarabic-bold.ttf
