// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYZcdeZQp-Fg2zyb4k8sfm-deuIPh1BY',
    appId: '1:468176692944:web:38b8be404745e6149ae0d5',
    messagingSenderId: '468176692944',
    projectId: 'intaliocts',
    authDomain: 'intaliocts.firebaseapp.com',
    storageBucket: 'intaliocts.appspot.com',
    measurementId: 'G-N7YFTE78QW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqd-hfsM6A_IPMzrhMl3Xh7Kid4Cy4No',
    appId: '1:468176692944:android:95206b61c21e09e19ae0d5',
    messagingSenderId: '468176692944',
    projectId: 'intaliocts',
    storageBucket: 'intaliocts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_LoRsjMFHaULoG5a_Lv5QGMVPNkb1LVs',
    appId: '1:468176692944:ios:55927636dae814c89ae0d5',
    messagingSenderId: '468176692944',
    projectId: 'intaliocts',
    storageBucket: 'intaliocts.appspot.com',
    iosClientId: '468176692944-hqc485ea1s3v0kf5e2erppsoipq6q1l9.apps.googleusercontent.com',
    iosBundleId: 'com.intalio.newcmsdevtests',
  );
}
